# Docker
trigger:
- azure_dev

resources:
  containers:
  - container: redis
    image: redis
    ports:
    - 6379:6379
pool:
  vmImage: 'ubuntu-latest'

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '0f994c3b-8654-4c97-baeb-620f9a3dc1fb'
  imageRepository: 'fileservice'
  containerRegistry: 'tunkzdevcr01.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Package
  displayName: Maven test and package jar
  jobs:
    - job: Build Deploy
      services:
        redis: redis
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'package'
        - task: Docker@2
          displayName: dockerLogin
          inputs:
             command: login
             containerRegistry: $(dockerRegistryServiceConnection)
        - task: Docker@2
          inputs:
            repository: $(imageRepository)
            dockerfile: $(dockerfilePath)
            command: 'build'
            tags: |
              $(tag)
        - task: Docker@2
          inputs:
            repository: $(imageRepository)
            dockerfile: $(dockerfilePath)
            command: 'push'
            tags: |
              $(tag)